<a href="https://colab.research.google.com/github/lukmanr/codenext/blob/master/Vector_Math_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectors and Tensors in TensorFlow

This notebook is designed to teach you about vector math, introduces the "tensor", and how to perform basic vector operations in TensorFlow.

First we define a couple 1-D vectors.  We represent the vectors as simple arrays in Python.

In [0]:
A = [1, 2, 4, 7]
B = [2, 5, 1, 3]

Now we will see how to multiply a vector by a constant, using plain Python.  To multiply a vector by a constant, you simply multiply each of the vector elements by that constant.  Here is a code example:

In [0]:
# multiply a vector by a constant c
c = 3

for i in range(4):
  A[i] = c * A[i]

print(A)

[9, 18, 36, 63]


Your turn:  Write code to multiply B by the constant 5.

Now try to update the code to multiply a vector by a constant so that it works on a vector of any length.  Make a copy of the code above, and change it so that it will work on a vector of any length. Hint: use the python ```len()``` function.

Now let's write code to add two vectors together.  To add two vectors, just add their elements.  Of course this is only valid if the two vectors have the same number of elements.  Here is a code example:

In [0]:
C = [0,0,0,0]

for i in range(4):
  C[i] = A[i] + B[i]

print(A, "+", B, "=", C)

[9, 18, 36, 63] + [2, 5, 1, 3] = [11, 23, 37, 66]


Can you update the addition code to work on a vector of any length?  This may be trickier than it sounds.  If you are having trouble, ask me for a hint.

Subtracting vectors works exactly the same as addition - you simply subtract each of the vector elements.  

1.   Update your code above to perform subtraction.  
2.   Wrap your code in two methods, one for addition, and one for subtraction, so you can pass two vectors of any size, and return the result of adding/subtracting them.



One more operation to learn before we learn how to do all this in TensorFlow.  We have covered addition and subtraction, but what about multiplication?  There are more than one way to multiply vectors.  The most common one we will see is called the "dot product".  The dot product is written like this:  $ A \cdot B $. The result of a dot product is a scalar.  The code below shows how to perform a dot product:

In [0]:
A_dot_B = (A[0] * B[0]) + (A[1] * B[1]) + (A[2] * B[2]) + (A[3] * B[3])
print(A_dot_B)

333


Now try to write a method that will perform the dot product on two vectors of any length.


Now we are ready to try TensorFlow!  First we have to import TensorFlow.  Note we use a special statement that starts with a $ to tell colab that we want to use TensorFlow 2.x in this notebook.  These commands are called "magic commands" and there are a lot of them available in colab notebooks.  You can read [the docs](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.03-Magic-Commands.ipynb) to learn more.

In [0]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x selected.


TensorFlow 2.x is a lot easier to use than TensorFlow 1.x.  I recommend you always use TensorFlow 2.x when coding something new in TensorFlow.  You might need to use TensorFlow 1.x if you are using someone else's code that was already written in TensorFlow 1.x.

Here is how we define the same vectors as we used before, in TensorFlow. 

In [0]:
A = tf.constant([1, 2, 4, 7])

B = tf.constant([2, 5, 1, 3])

print(A)
print(B)

tf.Tensor([1 2 4 7], shape=(4,), dtype=int32)
tf.Tensor([2 5 1 3], shape=(4,), dtype=int32)


Note that when we print the variables in TensorFlow, we get a different result than when we print in regular python.  TensorFlow calls these variables "tensors".  It also prints a couple other attributes, the "shape" of the Tensor, and the "dtype".  The "shape" tells us the dimensions and size of each dimension of the Tensor (in this case, 1-D of size 4). The dtype tells us the data type of the elements of the Tensor, in this case int32.  All of the elements of a Tensor must have the same dtype.  If we want to specify a different dtype, we can do that by passing a dtype attribute when we create the Tensor.  For example, here is how to create a Tensor that contains floating point numbers:

In [0]:
D = tf.constant([1, 2, 1, 3], dtype=float)
print(D)

tf.Tensor([1. 2. 1. 3.], shape=(4,), dtype=float32)


Let's add tensors.  This is easy in TensorFlow - just use the `tf.add` method:


In [0]:
C = tf.add(A, B)
print(C)

tf.Tensor([ 3  7  5 10], shape=(4,), dtype=int32)


Try defining two tensors of shape (5,), then adding them together using `tf.add`.

Multiplying a tensor by a constant is also easy, using the `tf.multiply` method:

In [0]:
tf.multiply(3, A)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  6, 12, 21], dtype=int32)>

There are a few different ways to do a dot product in TensorFlow.  One way is the `tf.tensordot` method.  It requires you to specify an "axis", or dimension, that you want to multiply.  This is because this method is designed to work with tensors of arbitrary shape.  You have to tell TensorFlow which dimension, or axis, you want to perform the dot product on.

In [0]:
tf.tensordot(A, B, 1)

<tf.Tensor: shape=(), dtype=int32, numpy=37>

You can also use `tf.reduce_sum(tf.multiply(x, y))`.  The method `tf.multiply` multiplies each element in x by the corresponding element of y.  The method `tf.reduce_sum` adds all the elements of a tensor.  Now use those two methods to perform the dot product of the two 5 rank tensors you defined above.