<a href="https://colab.research.google.com/github/lukmanr/codenext/blob/master/Vector_Math_in_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectors and Tensors in TensorFlow

This notebook introduces the "tensor", and how to perform basic vector operations in TensorFlow.

First we define a couple 1-D vectors, as we did in the notebook on Python.  We represent the vectors as simple arrays in Python.

In [0]:
A = [3, 8, 1, 2]
B = [-2, 5, 1, 4]

Let's do a quick review of the last thing we learned about vector math in Python.  Recall:  there are more than one way to multiply vectors.  The most common one we will see is called the "dot product".  The dot product is written like this:  $ A \cdot B $. The result of a dot product is a scalar.  The code below shows how to perform a dot product:

In [0]:
A_dot_B = (A[0] * B[0]) + (A[1] * B[1]) + (A[2] * B[2]) + (A[3] * B[3])
print(A_dot_B)

43


Now write a method using a for loop that will perform the dot product on two vectors.  Use the method to multiply A and B.


Now we are ready to try TensorFlow!  First we have to import TensorFlow.  Note we use a special statement that starts with a $ to tell colab that we want to use TensorFlow 2.x in this notebook.  These commands are called "magic commands" and there are a lot of them available in colab notebooks.  You can read [the docs](https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.03-Magic-Commands.ipynb) to learn more.

In [0]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x is a lot easier to use than TensorFlow 1.x.  I recommend you always use TensorFlow 2.x when coding something new in TensorFlow.  You might need to use TensorFlow 1.x if you are using someone else's code that was already written in TensorFlow 1.x.

Here is how we define the same vectors as we used before, in TensorFlow. 

In [0]:
A = tf.constant([3, 8, 1, 2])

B = tf.constant([-2, 5, 1, 4])

print(A)
print(B)

tf.Tensor([3 8 1 2], shape=(4,), dtype=int32)
tf.Tensor([-2  5  1  4], shape=(4,), dtype=int32)


Note that when we print the variables in TensorFlow, we get a different result than when we print in regular python.  TensorFlow calls these variables "tensors".  It also prints a couple other attributes, the "shape" of the Tensor, and the "dtype".  The "shape" tells us the dimensions and size of each dimension of the Tensor (in this case, 1-D of size 4). The dtype tells us the data type of the elements of the Tensor, in this case int32.  All of the elements of a Tensor must have the same dtype.  If we want to specify a different dtype, we can do that by passing a dtype attribute when we create the Tensor.  For example, here is how to create a Tensor that contains floating point numbers:

In [0]:
D = tf.constant([1, 2, 1, 3], dtype=float)
print(D)

tf.Tensor([1. 2. 1. 3.], shape=(4,), dtype=float32)


Let's add tensors.  This is easy in TensorFlow - just use the `tf.add` method:


In [0]:
C = tf.add(A, B)
print(C)

tf.Tensor([ 3  7  5 10], shape=(4,), dtype=int32)


Try defining two tensors of shape (5,), then adding them together using `tf.add`.

Multiplying a tensor by a constant is also easy, using the `tf.multiply` method:

In [0]:
tf.multiply(3, A)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  6, 12, 21], dtype=int32)>

There are a few different ways to do a dot product in TensorFlow.  One way is the `tf.tensordot` method.  It requires you to specify an "axis", or dimension, that you want to multiply.  This is because this method is designed to work with tensors of arbitrary shape.  You have to tell TensorFlow which dimension, or axis, you want to perform the dot product on.

In [0]:
tf.tensordot(A, B, 1)

<tf.Tensor: shape=(), dtype=int32, numpy=37>

You can also use `tf.reduce_sum(tf.multiply(x, y))`.  The method `tf.multiply` multiplies each element in x by the corresponding element of y.  The method `tf.reduce_sum` adds all the elements of a tensor.  Now use those two methods to perform the dot product of the two 5 rank tensors you defined above.